title: "My Modern Site"
description: "A blog and data repository"
url: "https://kwdwrd.github.io"  # change to your real URL
baseurl: "/peeps"  # if using user site; for project site, set to "/REPO-NAME"

# Where Jekyll looks for posts
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  research:
    output: true
    permalink: /research/:title/
  analysis:
    output: true
    permalink: /analysis/:title/

defaults:
  - scope:
      path: ""
      type: research
    values:
      layout: post
  - scope:
      path: ""
      type: analysis
    values:
      layout: post

markdown: kramdown
theme: null
