title: "My Modern Site"
description: "A blog and data repository"
url: "https://kwdwrd.github.io"  # change to your real URL
baseurl: "/peeps"  # if using user site; for project site, set to "/REPO-NAME"

# Where Jekyll looks for posts
collections:
  posts:
    output: true

markdown: kramdown
theme: null

